### ISSUE TITLE
iOS build issue on latest version - v0.10.0

### ISSUE THREAD

**Issue by juanchoperezj** [nandorojo/burnt#13]
Version 0.9.0 was working just fine, the issue appeared in the last one.

React Native: 0.68.0
I checked the Swift version used on the project's build settings and it is Swift 5

<img width="519" alt="Screenshot 2023-03-07 at 5 20 13 PM" src="https://user-images.githubusercontent.com/17632690/223566741-05ab47a0-1768-4ce4-a0b5-25d34c7f36ee.png">

The last two lines disappeared after I remove the node modules and pods, then reinstall them and clean the build folder using Xcode, but the `Cannot find type 'Enumerable' in scope` it's still there.

<img width="1387" alt="Screenshot 2023-03-07 at 5 20 05 PM" src="https://user-images.githubusercontent.com/17632690/223566746-8fff8ec5-76ed-430d-8138-d4d7ddbdb90d.png">

**Comment by nandorojo** [comment]
@alantoa any idea? I saw you changed to `Enumerable` in #12

**Comment by nandorojo** [comment]
I think we may need to upgrade expo modules

**Comment by nandorojo** [comment]
A bit confused though, @alantoa said it was working for him. I wonder if we could get a repro made?

**Comment by alantoa** [comment]
@nandorojo yeah, I made the change because `EnumArgument` was deprecated in `expo-modules-core ` `v1.0.x`, the source code can be found [here](https://github.com/expo/expo/blob/95665447654242fab86c926f94520899f8c5f3c5/packages/expo-modules-core/ios/Swift/Arguments/Enumerable.swift#L24).

@juanchoperezj  so I guess you are using `expo-modules-core` version less than v1, right? if so, you need to upgrade it for it to work!

**Comment by juanchoperezj** [comment]
Thanks for the response @alantoa @nandorojo 

My bad, I was using Expo 45, and now it works fine!

But I do not see two lines on the toast on iOS. Text is: `In order to use the app, you must have internet connection`.

Toast config: 

```{
  title: 'No internet connection',
  message: 'In order to use the app, you must have internet connection.',
  preset: 'error',
  duration: 5,
}
```

<img width="549" alt="Screenshot 2023-03-16 at 12 35 15 PM" src="https://user-images.githubusercontent.com/17632690/225705493-eaa8ee4b-68e4-4f88-b0c3-d55eb81760f4.png">

**Comment by nandorojo** [comment]
I believe that's a limitation of `SPIndicator`: https://github.com/ivanvorobei/SPIndicator/blob/main/Sources/SPIndicator/SPIndicatorView.swift#L155

**Comment by nandorojo** [comment]
This isn't necessarily bad: Toasts should be very short and easy-to-read.

**Comment by juanchoperezj** [comment]
Agree! I just wanted to bring it out, I'll close the issue! Thanks for the help!
