### ISSUE TITLE
Readme app.json docs cause linting warning, breaking build

### ISSUE THREAD

**Issue by benschac** [nandorojo/burnt#15]
```
export default {
  plugins: [
    [
      "expo-build-properties",
      {
        ios: {
          deploymentTarget: "13.0",
        },
      },
    ],
  ],
};
```

I'm using `app.json` and have `expo tools` vscode extension running

Getting a warning of `Incorrect type. Expected one of string.`

Currently running expo 48 with create tamagui

**Comment by nandorojo** [comment]
i don’t understand what the issue is from what you wrote

**Comment by benschac** [comment]
Sorry, I should have given a bit more context.

~~I'm going step-by-step for installing the burnt package in my expo application with `create-tamagui`. My editor is giving me a warning that the configuration provided in the documentation is invalid.~~

~~When running the application with the configuration provided above in my expo app, it'll crash. I can provide a reproduction repo if needed.~~

I just gave it another go and I'm no longer getting warnings in my editor from expo tools vscode plugin. This must have been something with my local config
