### ISSUE TITLE
Stopped working on iOS

### ISSUE THREAD

**Issue by rosskhanas** [nandorojo/burnt#16]
I just noticed in code `return BurntModule.toastAsync({ duration, ...options });` it seems ok for the web, but `BurntModule` does not have a `toastAsync` method on iOS.

**Comment by nandorojo** [comment]
ah shoot, i have to fix this, you’ll have to use 0.10 until i’m back at my laptop

**Comment by nandorojo** [comment]
Fixed in 0.11.3
