### ISSUE TITLE
Can't import toaster for web

### ISSUE THREAD

**Issue by Rimantovas** [nandorojo/burnt#17]
There is no export for 'burnt/web'

![Screenshot 2023-05-09 at 19 52 02](https://github.com/nandorojo/burnt/assets/65122943/99a1d482-a1a3-4628-8075-f8386ccdafd2)

**Comment by nandorojo** [comment]
ah i forgot to add this to the release, will do it when i’m at my laptop

**Comment by Xander0x** [comment]
@nandorojo, did you end up adding this to the release? cheers for making this repo by the way. Has come in very useful.

**Comment by clayrisser** [comment]
@nandorojo cheers! Thank you for making this. Patiently waiting for the release.

**Comment by nandorojo** [comment]
Thanks for waiting here guys, just published this in `0.11.5`
