### ISSUE TITLE
How can we trigger multiple toasts ?

### ISSUE THREAD

**Issue by raphaelm-gioa** [nandorojo/burnt#18]
Hi ! Thanks for the awesome library

Currently when triggering multiple toasts; one just stacks one of top of the other in the z-axis.
How could we trigger multiple to be stacked on the y-axis to stack vertically ?

thanks !

**Comment by nandorojo** [comment]
that would be awesome to have, and we only have it on web for now. it would require a PR with the upstream SPIndicator library

**Comment by nandorojo** [comment]
Closing as I don't know how possible this is.
