### ISSUE TITLE
Using without Expo config

### ISSUE THREAD

**Issue by baronha** [nandorojo/burnt#20]
I'm using React Native Cli and not using Expo Config. How can I use this library?

![simulator_screenshot_62A80D6F-0ED0-490A-BC72-3CC77EFD36A0](https://github.com/nandorojo/burnt/assets/23580920/bf1ae330-b742-42a6-a2ce-6bbceaa4723c)

**Comment by alantoa** [comment]
@baronha hey, just need to make sure you are installed Expo modules. here is an installation guide: https://docs.expo.dev/bare/installing-expo-modules/#manual-installation

**Comment by bryanltobing** [comment]
is there a plan to make this work without expo module ? I have a react native project generated with react native cli that needs to support iOS 12 where expo module requires iOS 13

**Comment by nandorojo** [comment]
There aren’t plans for that. Why does it need to support iOS 12 out of curiosity?

![IMG_3192](https://github.com/nandorojo/burnt/assets/13172299/c9d5b7d5-c418-4f0d-8945-61e72f95eb06)

**Comment by nandorojo** [comment]
The expo instructions set the minimum version to 13.

**Comment by baronha** [comment]
> 

@nandorojo Back to the problem. Can't React Native CLI use this package?

**Comment by nandorojo** [comment]
> @baronha hey, just need to make sure you are installed Expo modules. here is an installation guide: https://docs.expo.dev/bare/installing-expo-modules/#manual-installation

Yes, with these instructions.

**Comment by baronha** [comment]
Thanks @nandorojo =((
