### ISSUE TITLE
Cannot find native module 'Burnt'

### ISSUE THREAD

**Issue by andordavoti** [nandorojo/burnt#21]
Tried installing this in an Expo Managed project, already using multiple packages that need pre building, without luck. Seems like it can't find the native module for some reason.

**I tried the following:**
- Deleting node_modules
- "yarn cache clean"
- Deleting the iOS folder
- Clearing the derived data for the project in xcode
- "npx expo prebuild --clean"
- "npx expo run:ios"

Am I missing something?

**Comment by nandorojo** [comment]
that all sounds right. which version are you on

**Comment by andordavoti** [comment]
I'm on Expo SDK v48.0.18

**Comment by andordavoti** [comment]
No, I don't see any mention of Burnt when installing the pods manually. More specifically, it's not in the list of libraries that gets auto linked, where I guess it should be?

**Comment by nandorojo** [comment]
Weird. Does this reproduce in an empty expo project?

**Comment by andordavoti** [comment]
It does. Just initialized a new project with the expo cli, then followed the steps in the installation guide, got the same error. Pushed up the repo to GitHub, including the native projects so you can see the Podfile.lock. Can't see Burnt mentioned there.

Link to repo: https://github.com/andordavoti/burnt-issue-21-reproduction

**Comment by nandorojo** [comment]
Thanks for sharing, I’ll look into this. I wonder if 0.11.4 works or nkt

**Comment by andordavoti** [comment]
Tried 0.11.4 in the same sample project I shared above without success.

**Comment by hirbod** [comment]
Actually, I just stumbled across the same issue and came here to see if anybody else reported it. We've upgraded the version at Showtime from 0.10 to 0.11.5 and the same issue happened. Cleared all deps, installed pods etc. 

Will downgrade for now and see if that helps

**Comment by thj-dk** [comment]
I'm getting this error on the latest 0.11.7.

**Comment by GenerousDev** [comment]
I am currently getting this error on my simulator with espo

**Comment by leonardoballand** [comment]
same here, Burnt 0.11.7, RN 0.72.4 bare project. It asked me to install expo-modules-core first. Now I got the same error message as above :(

**Comment by nandorojo** [comment]
It works fine for me on the latest version. It won’t work with expo go. Be sure to rebuild your native app.

**Comment by moishinetzer** [comment]
I'm getting this issue with the latest version of expo and this package

**Comment by SeanBarker182** [comment]
@moishinetzer Did you find a solution?

**Comment by moishinetzer** [comment]
I was able to get it working, but I had to delete my lockfile and all node_modules and all native folders. I then reinstalled everything from scratch. Only after all of that did I run the prebuild command and expo run:ios.

**Comment by alzalabany** [comment]
same issue in 12.2

**Comment by rgomezp** [comment]
Getting the same issue on 12.2.

I'm getting it in my tests.

I can mock it, but I feel like this should be working out of the box.

**Comment by VGerris** [comment]
Same for me, Burnt 12.2 , SDK 51, MacOS 15.2 M1 Max. Upgrading to SDK 52 gives me a crashing Expo Go. Using Tamagui Free starter.

**Comment by aoterolorenzo** [comment]
I think we all just would want to play with Expo Go in the development and ensure having a cool library for the toast/alerts once moved to a development client or prod, which is now kind of a pain because of the limitation of not having Burnt natively in Expo Go.

Because of that, I created this solution for my development environment.

 **burtn-wrapper.ts**
```
import { Alert } from 'react-native';
import React from 'react';

// Define the options interface based on Burnt's API
interface NotificationOptions {
  title: string;
  message?: string;
  preset?: 'done' | 'error' | 'none' | 'custom' | 'heart';
  duration?: number;
  haptic?: 'success' | 'warning' | 'error' | 'none';
  shouldDismissByDrag?: boolean;
  from?: 'top' | 'bottom';
  layout?: {
    iconSize?: {
      height?: number;
      width?: number;
    };
  };
  icon?: {
    ios?: {
      name?: string;
      color?: string;
    };
    web?: React.ReactNode;
  };
}

// Fallback Implementations (using Alert)

const fallbackToast = (options: NotificationOptions) => {
  const alertTitle = options.preset === 'error' ? `Error: ${options.title}` : options.title;
  Alert.alert(alertTitle, options.message);
};

const fallbackAlert = (options: NotificationOptions) => {
  const alertTitle = options.preset === 'error' ? `Error: ${options.title}` : options.title;
  Alert.alert(alertTitle, options.message);
};

let toastImplementation = fallbackToast;
let alertImplementation = fallbackAlert;


try {
  // Try to load Real Burnt
  const RealBurnt = require('burnt');
  console.log("Successfully loaded burnt module.");

  toastImplementation = (options: NotificationOptions) => RealBurnt.toast(options);
  
  if (RealBurnt.alert) {
    alertImplementation = (options: NotificationOptions) => RealBurnt.alert(options);
  } else {
    console.log("RealBurnt.alert not found, using RealBurnt.toast as fallback for alerts.");
    alertImplementation = (options: NotificationOptions) => RealBurnt.toast(options); 
  }

} catch (error) {
  console.log("Failed to load burnt module. Using Alert fallback.", error);
  // Fallback implementations remain active
}

export const toast = toastImplementation;
export const alert = alertImplementation; 
```

This basically implements a fallback to `react-native`'s `Alert` when Burnt is not available. So you can just use this around your code, develop with all the calm of the world, using Burnt in Expo Go. Of course mind that all you will see in Expo Go will be basic/native toasts, but if you compile the project or create a development client you will see beautiful Burnt toasts/alerts.

```
import * as Burnt from '@/lib/utils/burtn-wrapper';


Burnt.toast({
  title: "Registration Successful",
  message: "Please check your email to confirm your account.",
  preset: "done", // Use 'done' preset for success checkmark
  duration: 4, // Optional: show for 4 seconds
  haptic: "success", // Optional: success haptic feedback
});
```

Happy toasting!
