### ISSUE TITLE
Unable to resolve "sonner"

### ISSUE THREAD

**Issue by timoisalive** [nandorojo/burnt#26]
Hmm, I'm getting
```
Unable to resolve "sonner" from "node_modules/burnt/build/web.js"
```

I have installed `sonner`, even tried an older version of it.

I'm running an Expo 49 project.

**Comment by nandorojo** [comment]
seems like something is up with metro web here

**Comment by timoisalive** [comment]
Ok, thanks for looking into it! I'll keep following the thread...

**Comment by bryanltobing** [comment]
not sure if this is the same case. but this is happening to me with `react-hook-form`. i added this and it fixes the issue

```diff

// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

config.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: true,
  },
});

+config.resolver.sourceExts.push('mjs');
+config.resolver.sourceExts.push('cjs');

module.exports = config;

```

**Comment by ducnguyen4301** [comment]
yup, I got the same error, even though I downloaded npm sooner

**Comment by nandorojo** [comment]
Did you try the workaround?

**Comment by ducnguyen4301** [comment]
> Did you try the workaround?

ye, The solution above helped me solve this problem

**Comment by nandorojo** [comment]
New Expo Web docs on the README have been added solving this.

**Comment by timoisalive** [comment]
Nice, thanks a bunch! 🙏
