### ISSUE TITLE
Possibility to modify width? 

### ISSUE THREAD

**Issue by gerzonc** [nandorojo/burnt#29]
Is it possible to modify width? I'm trying to show a message but is being cut off before finishing, not sure if it's something that can be done natively within the library? If so I can open a PR for it, thanks!

<img width="401" alt="image" src="https://github.com/nandorojo/burnt/assets/36211892/b8d1e3bb-774f-428c-8dab-9a934163393c">

**Comment by nandorojo** [comment]
It would require a PR for the upstream SPIndicator

**Comment by gerzonc** [comment]
Alright, will take a look, thanks! :)

**Comment by anthonysgro** [comment]
Hey @gerzonc , I saw your issue you posted on SPIndicator: https://github.com/ivanvorobei/SPIndicator/issues/27, but I don't understand their maintainer's response:

> Hello! I will move this package to AlertKit framework and add moving text. It should work for you

do you know if this was done? It was several years ago, and this seems like a pretty critical requirement for a UI element. Would love the ability to provide a custom width
