### ISSUE TITLE
Custom shadow colors/configuration options for the toast

### ISSUE THREAD

**Issue by fobos531** [nandorojo/burnt#3]
This is more of a feature request since I've found that the default shadow config applied by SPIndicator does not fit my use case. I don't know if SPIndicator exposes those parameters as configurable - if so, it would be nice to have the option to customize them, similar to how you can do so with regular react native View. This might be easier to do when Expo adds support for using SwiftUI views within the modules

**Comment by nandorojo** [comment]
It looks like `SPIndicator` doesn't allow this. However, `toast-swift` would allow it by using a custom View, which I don't know how to do but I imagine wouldn't be that hard. So it's another reason to try it (re #1).

https://github.com/BastiaanJansen/toast-swift#custom-toast-view

**Comment by nandorojo** [comment]
#11 implements some of this
