### ISSUE TITLE
Upgrading to Version 0.12.2 - index.ts:21 [burnt] toast() error: You need to add the <Toaster /> component to the root of your app for toasts to display on Web. There was no <Toaster /> found.

### ISSUE THREAD

**Issue by williamlmao** [nandorojo/burnt#34]
Getting this error after upgrading to 0.12.2: `index.ts:21 [burnt] toast() error: You need to add the <Toaster /> component to the root of your app for toasts to display on Web. There was no <Toaster /> found.`

I flipped back to 0.12.1, and the error went away and toasts started working again. I definitely have a toaster in my root layout file `app/layout.tsx` (using app router in nextjs 14.0.3).

Find this really weird because #33 didn't change a whole lot.

**Comment by nandorojo** [comment]
Hmm weird…open to a PR fixing this since I’m a little busy rn

**Comment by williamlmao** [comment]
Hey @nandorojo, yeah it's super weird. Little update here, even while I was on 0.12.1, at one point the error came back. Really not sure what caused it. Restarted my app, nothing. Upgraded to 0.12.2, and then the error went away.

Feels like it's some weird compile / bundle / package caching error. Anyways, it seems to be an intermittent error and some combination of restarting / upgrading and downgrading will fix it temporarily. 

Haven't noticed any issues in production either, only local.
