### ISSUE TITLE
Add Web Toast

### ISSUE THREAD

**Issue by mrzmyr** [nandorojo/burnt#7]
@nandorojo you were thinking of something with [`radix-ux` Toast](https://www.radix-ui.com/docs/primitives/components/toast)?

Alternatives:
- https://github.com/timolins/react-hot-toast
- https://github.com/fkhadra/react-toastify

**Comment by nandorojo** [comment]
It’s tough to say. Part of me wants to use Zeego to implement this part. I don’t love the Radix API for Toasts. It’s a bit too declarative for my liking. Hot Toast looks great, just have to decide which features to support.

**Comment by chrisarts** [comment]
React hot toast its really lite, and probably mixing it with externalStore to avoid using provider could achieve the same behaviour you have on android and iOS.

![Screenshot 2023-01-17 at 1 50 51 PM](https://user-images.githubusercontent.com/3628422/212986167-cbfacb43-7688-46c3-8db0-b33b92106cbd.png)

**Comment by nandorojo** [comment]
For what it's worth: Tamagui has implemented a `Toast` component which uses Burnt on native (optionally). This was my original vision, and I think it may be the correct behavior for Burnt. But I might add support for [Sonner](https://github.com/emilkowalski/sonner) on Web, even though its APIs are quite different.

**Comment by nandorojo** [comment]
Web support has been added in `0.11`: https://github.com/nandorojo/burnt/releases/tag/v0.11

**Comment by mrzmyr** [comment]
❤️
