### ISSUE TITLE
ASN1Decoder pod install error

### ISSUE THREAD

**Issue by alfalfa-leeks** [nandorojo/burnt#9]
```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Error installing ASN1Decoder
[!] /usr/local/bin/git clone https://github.com/filom/ASN1Decoder.git /var/folders/p4/429v7kqd02n3c2qhrt0n94y40000gn/T/d20230114-47934-qn4xhk --template= --single-branch --depth 1 --branch 1.8.0

Cloning into '/var/folders/p4/429v7kqd02n3c2qhrt0n94y40000gn/T/d20230114-47934-qn4xhk'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Used the solito instructions found here: https://github.com/nandorojo/burnt#solito
but instead of cd'ing into `applications/app` I went into `apps/expo` (i am using a tamagui starter project), and i also tried manually going in to the `ios` folder to `pod install` with no luck (same error above).

**Comment by nandorojo** [comment]
hmm it's not clear to me that this is a burnt issue..is your XCode on 14.2? and updated cocoa pods?

**Comment by nandorojo** [comment]
the error is pointing at `ASN1Decoder `, I wonder what uses that
